language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
before_install:
  - pip install -U pip
install:
  - pip install -e .
  - pip install -U beautifulsoup4 pytest pytest-mock werkzeug
script: py.test
