[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "crosscompute"
dynamic = ["version"]
# dependencies = []
# requires-python = ""
# authors = []
# maintainers = []
# description = ""
# readme = "README.md"
# keywords = []
# classifiers = []

[project.optional-dependencies]

[project.urls]
# Homepage = ""
# Documentation = ""
# Repository = ""
# Issues = ""
# Changelog = ""

[project.scripts]
crosscompute = "crosscompute.script.launch:run"

[tool.hatch.build]
packages = ["sources/crosscompute"]

[tool.hatch.version]
path = "sources/crosscompute/__init__.py"
