[coverage:run]
parallel = true
branch = true
source = crosscompute,

[coverage:paths]
source = crosscompute,.tox/*/site-packages

[flake8]
max-line-length = 79
select = C,E,F,W,B,B950
ignore = E501,W503,E203

[tox]
envlist = lint,py35,py36,py37,py38,coverage-report

[testenv]
deps =
    .[test]
commands=
    coverage run -m pytest tests

[testenv:coverage-report]
deps = coverage
skip_install = true
commands =
    coverage combine
    coverage report

[testenv:lint]
deps = flake8
skip_install = true
commands=
    flake8 crosscompute

[gh-actions]
python =
    3.5: py35
    3.6: py36
    3.7: lint,py37
    3.8: py38
